### PR TITLE
Vasil HF

### PR DESCRIPTION
**Pull request by sorki**
* Bunch of other changes to sync with openapi spec.
* `Preprod` and `Preview` environments

### CODE REVIEW

**Comment by nhenin** [comment]
Hi, I have tried to integrate your new version supporting the new environnement Preprod/Preview but I have discovered that cardano-wallet is using your api with the following constraint : `blockfrost-api>=0.4 && <0.5`, what is the status regarding that ? is there a branch on cardano-wallet where the upgdrae is done ? Thx

**Comment by sorki** [comment]
> 

Hi! I'm not really involved in cardano-wallet + blockfrost-haskell integration, only aware of it. I see the linked PR - did you encounter any issues? If not I would proceed with the release today.

**Comment by TotallyNotChase** [comment]
@nhenin You should actually be able to utilize `allow-newer` in your cabal.project to ignore that constraint on the cardano-wallet side. It should still compile (using commit ref: `18a931648550246695c790578d4a55ee2f10463e`, synced with node 1.35.3 and plutus-apps `721aa31863667d1a08d5d966420d7b093a348847`). I had successfully managed to compile this branch of blockfrost-haskell with those versions.

```
allow-newer:
  cardano-wallet:blockfrost-api,
  cardano-wallet:blockfrost-client,
  cardano-wallet:blockfrost-client-core
```

**Comment by TotallyNotChase** [comment]
Also just going to pop in here to say thanks again @sorki for the quick `Double` -> `Rational` fix :)

**Comment by sorki** [comment]
I've force pushed the branch to have version bump commit on top (I'm sorry if I caused a breakage) and will release as `0.6` after CI finishes.

Note that some calls might fail on mainnet until it hardforks - most notably protocol parameters as mainnet API won't  return cost models just yet.

**Pull request merged**
