### PR TITLE
api : add account associated addresses endpoint

### PR DESCRIPTION
**Pull request by nhenin**

### CODE REVIEW

**Comment by sorki** [comment]
Thank you! It looks good but there's a small catch - the response has the addresses wrapped in another object

```json
[
  {
    "address": "addr1qx2kd28nq8ac5prwg32hhvudlwggpgfp8utlyqxu6wqgz62f79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9sy0f4qd"
  },
  {
    "address": "addr1q8j55h253zcvl326sk5qdt2n8z7eghzspe0ekxgncr796s2f79qsdmm5dsknt9ecr5w468r9ey0fxwkdrwh08ly3tu9sjmd35m"
  }
]
```

instead of just "list of strings" so we need a `newtype` wrapper that parses this. There are some examples like `ScriptCBOR` or `ScriptDatum` if you want to try.

**Comment by nhenin** [comment]
Hi @sorki, yes sorry I knew it... got distracted before finishing it....  why are you not only returning an array of string without the field address ? I could have mapped `[Address]` instead of using an newtype like I juste did...

**Comment by mmahut** [comment]
@nhenin the reason is that if we would eventually need to add a new field/information in the future, we would not have to introduce a breaking change into the API by converting the array of string into an array of objects.

**Comment by sorki** [comment]
Merged as part of #9 and released on Hackage. Thanks!

**Pull request closed without merging**
